In [2]:
import numpy as np

In [5]:
one_d_array = np.array([10,12])
one_d_array.shape
print(one_d_array)

[10 12]


In [8]:
b=np.arange(10,20,5)
print(b)

[10 15]


In [11]:
c = np.arange(start=1,stop=20,step=3)
c

array([ 1,  4,  7, 10, 13, 16, 19])

In [14]:
d = np.linspace(0,100,5,dtype=int)
d

array([  0,  25,  50,  75, 100])

In [20]:
e = np.array(['Welcome to me','Hi'])
e.dtype

dtype('<U13')

In [22]:
f = np.zeros(3)
f

array([0., 0., 0.])

In [24]:
g = np.ones(3)
g

array([1., 1., 1.])

In [29]:
# Return a new array of shape 3, without initializing entries.
empt_arr = np.empty(3)
print(empt_arr[0])

1.0


In [30]:
i = np.random.rand(3)
i

array([0.27068613, 0.7020218 , 0.14218778])

In [33]:
two_d_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
two_d_array.shape


(3, 3)

In [38]:
arr = np.array([1,2,3,4,5,6])
new_arr= np.reshape(arr,(2,3))
new_arr.shape


(2, 3)

In [39]:
new_arr.size

6

In [40]:
new_arr.ndim

2

In [41]:
a = ([1,2,3,4])
a[0]

1

In [46]:
arr = np.array([1,2,3,4,5,6])
arr[::-1]

array([6, 5, 4, 3, 2, 1])

In [69]:
arr = np.array([[1,2,3,4],[2,3,4,4],[3,4,5,4]])
arr[:,1]

array([2, 3, 4])

In [76]:
a1 = np.array([[1,1],[2,2]])
a2 = np.array([[3,3],[4,4]])
print(a1.shape)

(2, 2)


In [78]:
a3 = np.vstack((a1,a2))
print(a3)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [79]:
a3 = np.hstack((a1,a2))
print(a3)

[[1 1 3 3]
 [2 2 4 4]]
