In [1]:
import numpy as np

In [3]:
A = np.array([[4,9,9],[9,1,6],[9,2,3]])

B = np.array([[2, 2], [5, 7], [4, 4]])


In [4]:
A.shape

(3, 3)

In [5]:
B.shape

(3, 2)

In [6]:
np.matmul(A,B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [7]:
A @ B

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [11]:
x = np.array([1, -2, -5]).reshape(3,1)
y = np.array([4, 3, -1]).reshape(3,1)
x.shape

(3, 1)

In [12]:
np.matmul(x,y)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

In [13]:
np.dot(A,B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])