In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
A = np.array([[2, 3],[2, 1]])
e1 = np.array([[1],[0]])
e2 = np.array([[0],[1]])

In [10]:
eig_values,eig_vectors=np.linalg.eig(A)

In [13]:
for n in eig_values:
    print(n)

4.0
-1.0


In [16]:
for n in eig_vectors:
    print(np.linalg.norm(n))

1.0919284281983377
0.898717034272917


In [18]:
A = np.array([[-1,0],[0,1]])
eig_value,eig_vectors = np.linalg.eig(A)

In [22]:
P = np.array([    
    [0, 0.75, 0.35, 0.25, 0.85],
    [0.15, 0, 0.35, 0.25, 0.05],
    [0.15, 0.15, 0, 0.25, 0.05],
    [0.15, 0.05, 0.05, 0, 0.05],
    [0.55, 0.05, 0.25, 0.25, 0]
]) 
X = np.array([[0], [0], [0], [1], [0]])

np.matmul(P,X)

array([[0.25],
       [0.25],
       [0.25],
       [0.  ],
       [0.25]])

In [23]:
m = 20 
for i in range(m):
    X = P @ X
print(X)

[[0.39392366]
 [0.13392366]
 [0.11407667]
 [0.0850993 ]
 [0.27297672]]


In [24]:
np.linalg.eig(P)

(array([ 1.        , -0.70367062,  0.00539505, -0.08267227, -0.21905217]),
 array([[-0.76088562, -0.81362074,  0.10935376,  0.14270615, -0.39408574],
        [-0.25879453,  0.050269  , -0.6653158 ,  0.67528802, -0.66465044],
        [-0.2204546 ,  0.07869601, -0.29090665,  0.17007443,  0.35048734],
        [-0.1644783 ,  0.12446953,  0.19740707, -0.43678067,  0.23311487],
        [-0.52766004,  0.56018621,  0.64946163, -0.55128793,  0.47513398]]))