In [1]:
from sympy import * 

sqrt(18)

3*sqrt(2)

In [2]:
N(sqrt(18),8)

4.2426407

In [3]:
x, y = symbols('x y')

expr = 2*x**2 - x*y

expr

2*x**2 - x*y

In [4]:
expr_manip = x * (expr + x * y + x**3)
expr_manip

x*(x**3 + 2*x**2)

In [5]:
expand(expr_manip)

x**4 + 2*x**3

In [6]:
factor(expr_manip)

x**3*(x + 2)

In [8]:
expr.evalf(subs = {x:2, y:4})

0.e-124

In [9]:
import numpy as np

In [10]:
A = np.array([1,2,3])

f = x**2

try:
    f(A)
except TypeError as err:
    print(err)


'Pow' object is not callable


In [13]:
from sympy.utilities.lambdify import lambdify

f_numpy_friendly = lambdify(x , f , 'numpy')

print("Array: \n", A)
print("f(x) = x**2: \n", f_numpy_friendly(A))

Array: 
 [1 2 3]
f(x) = x**2: 
 [1 4 9]


In [14]:
diff(x**3,x)

3*x**2

In [21]:
f = exp(-2*x) + 3*sin(3*x)

print(f)

dfdx = diff(f,x)

print(dfdx)


3*sin(3*x) + exp(-2*x)
9*cos(3*x) - 2*exp(-2*x)


In [27]:
A = np.array([1,2,3])

f = x**2

dfdx = diff(f,x)
print(dfdx)

dfdx_numpy_friendly = lambdify(x,dfdx,'numpy')

print(dfdx_numpy_friendly)

2*x
<function _lambdifygenerated at 0x7fed581b9d30>


In [28]:
print(dfdx_numpy_friendly(A))

[2 4 6]


In [30]:
dfdx_abs = diff(abs(x),x)
print(dfdx_abs)

(re(x)*Derivative(re(x), x) + im(x)*Derivative(im(x), x))*sign(x)/x


In [34]:
dfdx_abs.evalf(-2)

(re(x)*Derivative(re(x), x) + im(x)*Derivative(im(x), x))*sign(x)/x

In [36]:
dfdx_abs_numpy_friendly = lambdify(x,dfdx_abs,'numpy')
try :
    dfdx_abs_numpy_friendly(A)
except NameError as err:
     print(err)

name 'Derivative' is not defined


In [42]:
def f(x):
    return x**2

arr = np.linspace(-5 ,5, 100)
dfdx_numerical = np.gradient(f(arr),arr)
print(dfdx_numerical)

[-9.8989899  -9.7979798  -9.5959596  -9.39393939 -9.19191919 -8.98989899
 -8.78787879 -8.58585859 -8.38383838 -8.18181818 -7.97979798 -7.77777778
 -7.57575758 -7.37373737 -7.17171717 -6.96969697 -6.76767677 -6.56565657
 -6.36363636 -6.16161616 -5.95959596 -5.75757576 -5.55555556 -5.35353535
 -5.15151515 -4.94949495 -4.74747475 -4.54545455 -4.34343434 -4.14141414
 -3.93939394 -3.73737374 -3.53535354 -3.33333333 -3.13131313 -2.92929293
 -2.72727273 -2.52525253 -2.32323232 -2.12121212 -1.91919192 -1.71717172
 -1.51515152 -1.31313131 -1.11111111 -0.90909091 -0.70707071 -0.50505051
 -0.3030303  -0.1010101   0.1010101   0.3030303   0.50505051  0.70707071
  0.90909091  1.11111111  1.31313131  1.51515152  1.71717172  1.91919192
  2.12121212  2.32323232  2.52525253  2.72727273  2.92929293  3.13131313
  3.33333333  3.53535354  3.73737374  3.93939394  4.14141414  4.34343434
  4.54545455  4.74747475  4.94949495  5.15151515  5.35353535  5.55555556
  5.75757576  5.95959596  6.16161616  6.36363636  6

In [45]:
%pip install jax 

DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
Note: you may need to restart the kernel to use updated packages.


In [1]:
from jax import grad, vmap

import jax.numpy as jnp 

arr = jnp.array([1,2,3])
print(type(arr))

RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.

In [2]:
%pip install jaxlib

  Obtaining dependency information for jaxlib from https://files.pythonhosted.org/packages/63/a0/9cadd761fed0cf85bbf4b2162bcde799708dd07c5a7e8ab1a39d0c0a75a1/jaxlib-0.4.13-cp38-cp38-macosx_10_14_x86_64.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.0/75.0 MB 5.9 MB/s eta 0:00:0000:0100:01
DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
Note: you may need to restart the kernel to use updated packages.
